In [ ]:
#Importo librerias
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score , mean_absolute_error
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
#Leer los datos excell
fich = "datos1.xls"
df = pd.read_excel(fich)
df

    EDAD    SEXO FUMADOR    POBLACION NACIONALIDAD   ESTUDIOS  ENFERMEDAD
0     29  HOMBRE      SI   VALDESALOR     ESPAÑOLA  DIPLOMADO       0.875
1     18  HOMBRE      NO    PLASENICA     FRANCESA      GRADO       0.421
2     23   MUJER      SI        CORIA   VENEZOLANA     MASTER       0.245
3     37   MUJER       A      CACERES    ARGENTINA  DIPLOMADO       0.455
4     45   MUJER      NO      MONTIJO     ESPAÑOLA      GRADO       0.111
5     31   MUJER      SI       MERIDA    ARGENTINA     MASTER       0.985
6     28  HOMBRE      NO        CORIA   VENEZOLANA  DIPLOMADO       0.845
7     19  HOMBRE       A        CORIA     ESPAÑOLA      GRADO       0.187
8     28  HOMBRE       A    PLASENICA    ARGENTINA      GRADO       0.658
9     20   MUJER      NO   VALDESALOR   VENEZOLANA  DIPLOMADO       0.134
10    26   MUJER       A       MERIDA     ESPAÑOLA     MASTER       0.598
11    27   MUJER      SI       MERIDA     FRANCESA     MASTER       0.325
12    53   MUJER      NO       MERIDA     ESPAÑOLA  DIPLOMADO       0.911
13    55   MUJER      NO      CACERES   VENEZOLANA      GRADO       0.988
14    19  HOMBRE      SI      BADAJOZ     FRANCESA      GRADO       0.755
15    36   MUJER       A  TALARRUBIAS     ESPAÑOLA     MASTER       0.885
16    35  HOMBRE      NO      BADAJOZ     ESPAÑOLA  DIPLOMADO       0.236
17    50  HOMBRE      SI        CORIA     ESPAÑOLA     MASTER       0.248
18    59  HOMBRE       A    PLASENICA    ARGENTINA  DIPLOMADO       0.124
19    23  HOMBRE      SI    PLASENICA     ESPAÑOLA     MASTER       0.125
20    29   MUJER      SI        CORIA     ESPAÑOLA  DIPLOMADO       0.658
21    18   MUJER      SI        CORIA    ARGENTINA      GRADO       0.134
22    23   MUJER      SI    PLASENICA    ARGENTINA     MASTER       0.598
23    37  HOMBRE       A    PLASENICA     ESPAÑOLA  DIPLOMADO       0.325
24    45   MUJER       A        CORIA     ESPAÑOLA      GRADO       0.911
25    31  HOMBRE       A  TALARRUBIAS    ARGENTINA      GRADO       0.988
26    28  HOMBRE       A    PLASENICA     ESPAÑOLA  DIPLOMADO       0.755
27    19  HOMBRE      NO        CORIA     FRANCESA     MASTER       0.885
28    28  HOMBRE      SI    PLASENICA   VENEZOLANA     MASTER       0.236
29    20   MUJER       A  TALARRUBIAS    ARGENTINA  DIPLOMADO       0.248
30    26  HOMBRE       A    PLASENICA     ESPAÑOLA      GRADO       0.124
31    27  HOMBRE      SI        CORIA    ARGENTINA      GRADO       0.125
32    53  HOMBRE      SI  TALARRUBIAS   VENEZOLANA     MASTER       0.658
33    55  HOMBRE      SI    PLASENICA     ESPAÑOLA  DIPLOMADO       0.134
34    19   MUJER      NO  TALARRUBIAS    ARGENTINA     MASTER       0.598
35    36   MUJER      NO  TALARRUBIAS   VENEZOLANA  DIPLOMADO       0.325
36    35   MUJER      NO    PLASENICA   VENEZOLANA     MASTER       0.911
37    50   MUJER       A        CORIA     ESPAÑOLA  DIPLOMADO       0.988
38    59  HOMBRE       A    PLASENICA    ARGENTINA     MASTER       0.755
39    23  HOMBRE       A    PLASENICA   VENEZOLANA  DIPLOMADO       0.885

In [ ]:
#Numero de celdas
df.size

280

In [ ]:
#Estructura filas y columnas
df.shape

(40, 7)

In [ ]:
#Filas
df.shape[0]

40

In [ ]:
#Columnas
df.shape[1]

7

In [ ]:
#Tipos de datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EDAD          40 non-null     int64
 1   SEXO          40 non-null     object
 2   FUMADOR       40 non-null     object
 3   POBLACION     40 non-null     object
 4   NACIONALIDAD  40 non-null     object
 5   ESTUDIOS      40 non-null     object
 6   ENFERMEDAD    40 non-null     float64
dtypes: float64(1), int64(1), object(5)
memory usage: 2.3+ KB

In [ ]:
#Columnas
df.columns

Index(['EDAD', 'SEXO', 'FUMADOR', 'POBLACION', 'NACIONALIDAD', 'ESTUDIOS',
       'ENFERMEDAD'],
      dtype='object')

In [ ]:
#Pasar object a categoricas
df['SEXO'] = pd.Categorical(df['SEXO'])
df['FUMADOR'] = pd.Categorical(df['FUMADOR'])
df['POBLACION'] = pd.Categorical(df['POBLACION'])
df['NACIONALIDAD'] = pd.Categorical(df['NACIONALIDAD'])
df['ESTUDIOS'] = pd.Categorical(df['ESTUDIOS'])

In [ ]:
#Tipos de datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EDAD          40 non-null     int64
 1   SEXO          40 non-null     category
 2   FUMADOR       40 non-null     category
 3   POBLACION     40 non-null     category
 4   NACIONALIDAD  40 non-null     category
 5   ESTUDIOS      40 non-null     category
 6   ENFERMEDAD    40 non-null     float64
dtypes: category(5), float64(1), int64(1)
memory usage: 1.9 KB

In [ ]:
#Columnas dummies
gender_dummy = pd.get_dummies(df['SEXO'], prefix='SEXO')
df = pd.concat([df, gender_dummy], axis=1)


df = df.drop(['SEXO'], axis = 1)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EDAD          40 non-null     int64
 1   FUMADOR       40 non-null     category
 2   POBLACION     40 non-null     category
 3   NACIONALIDAD  40 non-null     category
 4   ESTUDIOS      40 non-null     category
 5   ENFERMEDAD    40 non-null     float64
 6   SEXO_HOMBRE   40 non-null     uint8
 7   SEXO_MUJER    40 non-null     uint8
dtypes: category(4), float64(1), int64(1), uint8(2)
memory usage: 1.8 KB

In [ ]:
#Cat codes
df['FUMADOR'] = df['FUMADOR'].cat.codes

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EDAD          40 non-null     int64
 1   FUMADOR       40 non-null     int8
 2   POBLACION     40 non-null     category
 3   NACIONALIDAD  40 non-null     category
 4   ESTUDIOS      40 non-null     category
 5   ENFERMEDAD    40 non-null     float64
 6   SEXO_HOMBRE   40 non-null     uint8
 7   SEXO_MUJER    40 non-null     uint8
dtypes: category(3), float64(1), int64(1), int8(1), uint8(2)
memory usage: 1.7 KB

In [ ]:
#LabelEncoder
encoder = LabelEncoder()
df["POBLACION"] = encoder.fit_transform(df["POBLACION"])
df

,EDAD,FUMADOR,POBLACION,NACIONALIDAD,ESTUDIOS,ENFERMEDAD,SEXO_HOMBRE,SEXO_MUJER
0,29,2,7,ESPAÑOLA,DIPLOMADO,0.875,1,0
1,18,1,5,FRANCESA,GRADO,0.421,1,0
2,23,2,2,VENEZOLANA,MASTER,0.245,0,1
3,37,0,1,ARGENTINA,DIPLOMADO,0.455,0,1
4,45,1,4,ESPAÑOLA,GRADO,0.111,0,1
5,31,2,3,ARGENTINA,MASTER,0.985,0,1
6,28,1,2,VENEZOLANA,DIPLOMADO,0.845,1,0
7,19,0,2,ESPAÑOLA,GRADO,0.187,1,0
8,28,0,5,ARGENTINA,GRADO,0.658,1,0
9,20,1,7,VENEZOLANA,DIPLOMADO,0.134,0,1
10,26,0,3,ESPAÑOLA,MASTER,0.598,0,1
11,27,2,3,FRANCESA,MASTER,0.325,0,1
12,53,1,3,ESPAÑOLA,DIPLOMADO,0.911,0,1
13,55,1,1,VENEZOLANA,GRADO,0.988,0,1
14,19,2,0,FRANCESA,GRADO,0.755,1,0
15,36,0,6,ESPAÑOLA,MASTER,0.885,0,1
16,35,1,0,ESPAÑOLA,DIPLOMADO,0.236,1,0
17,50,2,2,ESPAÑOLA,MASTER,0.248,1,0
18,59,0,5,ARGENTINA,DIPLOMADO,0.124,1,0
19,23,2,5,ESPAÑOLA,MASTER,0.125,1,0
20,29,2,2,ESPAÑOLA,DIPLOMADO,0.658,0,1
21,18,2,2,ARGENTINA,GRADO,0.134,0,1
22,23,2,5,ARGENTINA,MASTER,0.598,0,1
23,37,0,5,ESPAÑOLA,DIPLOMADO,0.325,1,0
24,45,0,2,ESPAÑOLA,GRADO,0.911,0,1
25,31,0,6,ARGENTINA,GRADO,0.988,1,0
26,28,0,5,ESPAÑOLA,DIPLOMADO,0.755,1,0
27,19,1,2,FRANCESA,MASTER,0.885,1,0
28,28,2,5,VENEZOLANA,MASTER,0.236,1,0
29,20,0,6,ARGENTINA,DIPLOMADO,0.248,0,1
30,26,0,5,ESPAÑOLA,GRADO,0.124,1,0
31,27,2,2,ARGENTINA,GRADO,0.125,1,0
32,53,2,6,VENEZOLANA,MASTER,0.658,1,0
33,55,2,5,ESPAÑOLA,DIPLOMADO,0.134,1,0
34,19,1,6,ARGENTINA,MASTER,0.598,0,1
35,36,1,6,VENEZOLANA,DIPLOMADO,0.325,0,1
36,35,1,5,VENEZOLANA,MASTER,0.911,0,1
37,50,0,2,ESPAÑOLA,DIPLOMADO,0.988,0,1
38,59,0,5,ARGENTINA,MASTER,0.755,1,0
39,23,0,5,VENEZOLANA,DIPLOMADO,0.885,1,0

In [ ]:
#Cat codes
df['NACIONALIDAD'] = df['NACIONALIDAD'].cat.codes
df['ESTUDIOS'] = df['ESTUDIOS'].cat.codes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EDAD          40 non-null     int64
 1   FUMADOR       40 non-null     int8
 2   POBLACION     40 non-null     int64
 3   NACIONALIDAD  40 non-null     int8
 4   ESTUDIOS      40 non-null     int8
 5   ENFERMEDAD    40 non-null     float64
 6   SEXO_HOMBRE   40 non-null     uint8
 7   SEXO_MUJER    40 non-null     uint8
dtypes: float64(1), int64(2), int8(3), uint8(2)
memory usage: 1.3 KB

In [ ]:
#Dividir el df en X e Y
X = df.drop('ENFERMEDAD', axis=1)
Y = df["ENFERMEDAD"]

In [ ]:
#Normalizar X
scaler = StandardScaler()
x1= scaler.fit_transform(X)

In [ ]:
#Aplicar train test split
X_train, X_test, y_train, y_test = train_test_split(x1, Y, test_size=0.2, random_state=0)

#Regresión Lineal

In [ ]:
from sklearn import linear_model

In [ ]:
# Creo un modelo de regresión lineal
modelo = linear_model.LinearRegression()

In [ ]:
X_train.shape

(32, 7)

In [ ]:
# Entreno el modelo con los datos (X,Y)
modelo.fit(X_train.reshape(32,7), y_train)

LinearRegression()

In [ ]:
X_test.shape

(8, 7)

In [ ]:
# Podemos predecir usando el modelo
y_pred = modelo.predict(X_test.reshape(8,7))

In [ ]:
# Por último, calculamos el error cuadrático medio y el estadístico R^2
print('Error cuadrático medio: %.2f' % mean_squared_error(y_test, y_pred))
print('Estadístico R_2: %.2f' % r2_score(y_test, y_pred))

Error cuadrático medio: 0.11
Estadístico R_2: -0.37

In [ ]:
mean_absolute_error(y_test, y_pred)

0.30397568927090174

#KNN vecinos

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV

In [ ]:
clf = KNeighborsRegressor()
params = {"n_neighbors": range(1, 20)}

In [ ]:
clf_gs = GridSearchCV(clf, params, cv=3)
clf_gs.fit(X_train.reshape(32,7), y_train)
print('El mejor estimador es: {}'.format(clf_gs.best_estimator_))

El mejor estimador es: KNeighborsRegressor(n_neighbors=4)

In [ ]:

y_axis_pred = clf_gs.best_estimator_.predict(X_test.reshape(8,7))

In [ ]:
# Por último, calculamos el error cuadrático medio y el estadístico R^2
print('Error cuadrático medio: %.2f' % mean_squared_error(y_test, y_axis_pred))
print('Estadístico R_2: %.2f' % r2_score(y_test, y_axis_pred))

Error cuadrático medio: 0.16
Estadístico R_2: -0.88

In [ ]:
mean_absolute_error(y_test, y_axis_pred)

0.31696875

#Arboles de decision

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
# Obtengo el mejor parámetro de profundidad del árbol entre 3 y 7 usando
# validación cruzada y gridsearch
regr = DecisionTreeRegressor()
params = {"max_depth": range(3, 7)}
regr_opt = GridSearchCV(regr, params, cv=3)
regr_opt.fit(X_train.reshape(32,7), y_train)
print('El mejor estimador es: {}'.format(regr_opt.best_estimator_))

El mejor estimador es: DecisionTreeRegressor(max_depth=5)

In [ ]:
y_test_pred = regr_opt.predict(X_test.reshape(8,7))

In [ ]:
# Por último, calculamos el error cuadrático medio y el estadístico R^2
print('Error cuadrático medio: %.2f' % mean_squared_error(y_test, y_test_pred))
print('Estadístico R_2: %.2f' % r2_score(y_test, y_test_pred))

Error cuadrático medio: 0.25
Estadístico R_2: -2.05

In [ ]:

mean_absolute_error(y_test, y_test_pred)

0.4575416666666667

#Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import cross_val_score, RepeatedKFold

In [ ]:
# Defino un modelo
model = RandomForestRegressor()

In [ ]:
import statistics
import numpy as np

In [ ]:
# Evalúo el modelo
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_train.reshape(32,7), y_train, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1, error_score='raise')
# Obtengo una métrica de rendimiento
print(u'Obtengo el error absoluto medio (MAE): %.3f, desviación %.3f' % (statistics.mean(n_scores), np.std(n_scores)))

Obtengo el error absoluto medio (MAE): -0.322, desviación 0.055

In [ ]:
# Ajusto el modelo a los datos
model.fit(X_train.reshape(32,7),y_train)
y_prediccion = model.predict(X_test.reshape(8,7))

In [ ]:
# Por último, calculamos el error cuadrático medio y el estadístico R^2
print('Error cuadrático medio: %.2f' % mean_squared_error(y_test, y_prediccion))
print('Estadístico R_2: %.2f' % r2_score(y_test, y_prediccion))

Error cuadrático medio: 0.14
Estadístico R_2: -0.64

In [ ]:

mean_absolute_error(y_test, y_prediccion)

0.3137724999999999

#XGBoost

In [ ]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (2.0.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.11.3)

In [ ]:
import xgboost as xgb

In [ ]:
# Obtengo el mejor parámetro de profundidad del árbol entre 3 y 7 usando
# validación cruzada y gridsearch
regr = xgb.XGBRegressor()
params = {"eta": [0.3, 0.5], "lambda":[0.5, 1.0], "max_depth": [3, 7]}
regr_opt = GridSearchCV(regr, params, cv=3)
regr_opt.fit(X_train.reshape(32,7), y_train)
print('Los mejores hiperparámetros son: {}'.format(regr_opt.best_params_))

Los mejores hiperparámetros son: {'eta': 0.5, 'lambda': 1.0, 'max_depth': 3}

In [ ]:

y_test_pred = regr_opt.predict(X_test.reshape(8,7))

In [ ]:
# Por último, calculamos el error cuadrático medio y el estadístico R^2
print('Error cuadrático medio: %.2f' % mean_squared_error(y_test, y_test_pred))
print('Estadístico R_2: %.2f' % r2_score(y_test, y_test_pred))

Error cuadrático medio: 0.15
Estadístico R_2: -0.86

In [ ]:

mean_absolute_error(y_test, y_test_pred)

0.32719128037989137

#SVM  Kernel RBF o Gaussiano

In [ ]:
from sklearn.svm import SVR

In [ ]:
# Ajuste del modelo de regresión
svr_rbf = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1)

In [ ]:
svr_rbf = SVR(verbose=True)

svr_rbf.fit(X_train.reshape(32,7), y_train)

y_pred = svr_rbf.predict(X_test.reshape(8,7))

[LibSVM]

In [ ]:
# Por último, calculamos el error cuadrático medio y el estadístico R^2
print('Error cuadrático medio: %.2f' % mean_squared_error(y_test, y_pred))
print('Estadístico R_2: %.2f' % r2_score(y_test, y_pred))

Error cuadrático medio: 0.13
Estadístico R_2: -0.59

In [ ]:

mean_absolute_error(y_test, y_pred)

0.28808421543948703

#SVM  Kernel Lineal

In [ ]:
from sklearn.svm import SVR

In [ ]:
# Ajuste del modelo de regresión
svr_lin = SVR(kernel='linear', C=100, gamma=0.1, epsilon=.1)

In [ ]:
svr_lin = SVR(verbose=True)

svr_lin.fit(X_train.reshape(32,7), y_train)

y_pred_lin = svr_lin.predict(X_test.reshape(8,7))

[LibSVM]

In [ ]:
# Por último, calculamos el error cuadrático medio y el estadístico R^2
print('Error cuadrático medio: %.2f' % mean_squared_error(y_test, y_pred_lin))
print('Estadístico R_2: %.2f' % r2_score(y_test, y_pred_lin))

Error cuadrático medio: 0.13
Estadístico R_2: -0.59

In [ ]:

mean_absolute_error(y_test, y_pred_lin)

0.28808421543948703

#SVM  Kernel Polinomico

In [ ]:
from sklearn.svm import SVR

In [ ]:
# Ajuste del modelo de regresión
svr_poly = SVR(kernel='poly', C=100, gamma=0.1, epsilon=.1)

In [ ]:
svr_poly = SVR(verbose=True)

svr_poly.fit(X_train.reshape(32,7), y_train)

y_pred_poly = svr_poly.predict(X_test.reshape(8,7))

[LibSVM]

In [ ]:
# Por último, calculamos el error cuadrático medio y el estadístico R^2
print('Error cuadrático medio: %.2f' % mean_squared_error(y_test, y_pred_poly))
print('Estadístico R_2: %.2f' % r2_score(y_test, y_pred_poly))

Error cuadrático medio: 0.13
Estadístico R_2: -0.59

In [ ]:

mean_absolute_error(y_test, y_pred_poly)

0.28808421543948703